'use client';
import { motion } from 'framer-motion';
const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.7 } };
export default function Education() {
  return <section id="education" className="py-24 px-6 bg-cream"><div className="max-w-[1100px] mx-auto">
    <motion.span {...reveal} className="inline-flex items-center gap-3 text-[10px] tracking-[0.38em] uppercase text-gold mb-3.5 before:content-[''] before:w-5 before:h-px before:bg-gold">Образование</motion.span>
    <motion.h2 {...reveal} transition={{...reveal.transition,delay:.1}} className="font-display font-light leading-tight text-navy" style={{fontSize:'clamp(32px,6vw,52px)'}}>Образование и профессиональная подготовка</motion.h2>
    <div className="gold-line w-12 my-5"/><div className="grid md:grid-cols-2 gap-8 mt-10">
      <motion.div {...reveal} className="bg-milk border border-navy/[0.06] rounded-sm p-7"><h3 className="font-display text-xl text-navy mb-5">Высшее медицинское образование</h3><ul className="space-y-4 text-sm leading-relaxed text-text-main"><li><strong>2017–2023:</strong> Кыргызская государственная медицинская академия им. И. К. Ахунбаева, факультет «Педиатрия».</li><li><strong>2024–2025:</strong> интернатура.</li><li><strong>2025–2028:</strong> ординатура по направлению «Дерматовенерология и косметология».</li></ul></motion.div>
      <motion.div {...reveal} className="bg-milk border border-navy/[0.06] rounded-sm p-7"><h3 className="font-display text-xl text-navy mb-5">Дополнительное образование и повышение квалификации</h3><ul className="space-y-3 text-sm leading-relaxed text-text-main list-disc pl-5"><li>2023 — подбор домашнего ухода и разбор составов косметики у Анастасии Кравц, Казахстан.</li><li>2023 — подготовка «Косметолог-эстетист», Beauty Med.</li><li>2024 — Skin Expert по химии косметических составов у Алисы Фурман, Москва.</li><li>2024 — курс «Внутренние причины развития акне» у Инны Дубровиной.</li><li>2025 — диагностика и лечение дерматофитий.</li><li>2025 — повышение квалификации у доцента Меньшиковой, Москва.</li></ul></motion.div>
    </div><motion.div {...reveal} className="mt-8 max-w-3xl"><h3 className="font-display text-xl text-navy mb-4">Изученные направления</h3><p className="text-sm leading-relaxed text-text-main">Диагностика и лечение акне, розацеа, дерматитов, псориаза, детская дерматология, заболевания кожи, связанные с ВПЧ, ретиноиды, болезни кожи стоп и ногтей, дерматофитии, подбор домашнего ухода и разбор косметических составов.</p><p className="text-sm leading-relaxed text-text-muted mt-5">Я регулярно прохожу дополнительные курсы, семинары, вебинары и специализированные программы. Оригиналы дипломов и сертификатов можно лично посмотреть в кабинете; полные изображения документов не публикуются для защиты персональных данных.</p></motion.div>
  </div></section>;
}
